version: 2
jobs:
  build_docs:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: |
          mkdir ~/my_test_artifacts
          echo "This should point to root_artifact.md for commit ${CIRCLE_SHA1}" > ~/my_test_artifacts/root_artifact.md
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: ~/my_test_artifacts
          destination: test_artifacts

workflows:
  version: 2
  default:
    jobs:
      - build_docs
